Create android.yml
PavelStalone/GestureTranslator pull request #6
Opened 2023-09-17 20:05 UTC by PavelStalone

2023-09-17 20:30 UTC, jacksever requested changes
Please check my comments

2023-09-17 20:30 UTC, jacksever commented on .github/workflows/android.yml
> +    - feature/*
```suggestion
    - feature/*
    - bugfix/*
    - hotfix/*
```

2023-09-17 20:30 UTC, jacksever commented on .github/workflows/android.yml
> +    branches: [ "main" ]
Repeat what was done above

2023-09-17 20:30 UTC, jacksever commented on .github/workflows/android.yml
> +    - name: set up JDK 17
```suggestion
    - name: Set up JDK 17
```

2023-09-17 20:30 UTC, jacksever commented on .github/workflows/android.yml
> +    - name: Build with Gradle
It is better to put it into parallel job :)

2023-09-17 20:31 UTC, PoroshinGA requested changes

2023-09-17 20:31 UTC, PoroshinGA commented on .github/workflows/android.yml
> +    branches: [ "main" ]
Why there's only one branch

2023-09-17 20:31 UTC, PavelStalone commented on .github/workflows/android.yml
> +    - name: Build with Gradle
Wait... What?

2023-09-18 16:47 UTC, jacksever commented on .github/workflows/android.yml
> +    - name: Build with Gradle
Repeat all code blocks that written above and create the new parallel job

2023-09-21 17:13 UTC, jacksever commented on .github/workflows/android.yml
> +
```
      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-
```

2023-09-21 17:30 UTC, PavelStalone commented
PR is here: #21

2023-09-21 17:31 UTC, jacksever approved these changes

2023-09-21 17:53 UTC, PoroshinGA approved these changes

2023-09-21 17:55 UTC, merged